backend/src/main/java/com/movie/demo/DemoApplication.java
backend/src/main/resources/application.yml
backend/src/test/java/com/movie/demo/DemoApplicationTests.java

[TC-3] Member Entity 매핑

---

backend/src/main/resources/application.yml

[TC-4] 회원가입 기능 구현

---

backend/src/main/java/com/movie/demo/member/entity/Member.java
backend/src/main/resources/application.yml

[TC-3] Memeber Entity 매핑

---

backend/src/main/java/com/movie/demo/member/entity/Member.java
backend/src/main/resources/application.yml

[TC-3] Member 앤티티 매핑

---

backend/src/main/java/com/movie/demo/member/controller/MemberController.java
backend/src/main/java/com/movie/demo/member/exception/MemberUsernameNotExistException.java
backend/src/main/java/com/movie/demo/member/exception/PasswordMisMatchException.java
backend/src/main/java/com/movie/demo/member/repository/MemberRepository.java
backend/src/main/java/com/movie/demo/member/request/LoginRequest.java
backend/src/main/java/com/movie/demo/member/response/LoginResponse.java
backend/src/main/java/com/movie/demo/member/service/MemberService.java
backend/src/main/java/com/movie/demo/member/service/MemberServiceImpl.java
backend/src/main/resources/application.yml

[TC-5] 로그인 인증 작업 구현

---

backend/gatchaPedia_BackEnd/build.gradle
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/handler/ExceptionManager.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/controller/MemberController.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/entity/Member.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/exception/MemberDuplicateByEmailException.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/exception/MemberDuplicateByNameException.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/exception/MemberDuplicateByUsernameException.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/exception/PasswordMisMatchException.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/request/LoginRequest.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/request/SignUpRequest.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/service/MemberService.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/service/MemberServiceImpl.java
backend/gatchaPedia_BackEnd/src/main/resources/application.yml

이미 존재하는 이름, 이메일, 아이디로 회원가입하는 경우예외처리

[TC-6] 이미 존재하는 이름, 이메일, 아이디로 회원가입하는 경우예외처리

---

backend/src/main/java/com/movie/demo/member/entity/Member.java
backend/src/main/resources/application.yml

[TC-3] Member 엔티티 매핑

---

backend/src/main/java/com/movie/demo/member/controller/MemberController.java
backend/src/main/java/com/movie/demo/member/entity/Member.java
backend/src/main/java/com/movie/demo/member/repository/MemberRepository.java
backend/src/main/java/com/movie/demo/member/request/SignUpRequest.java
backend/src/main/java/com/movie/demo/member/response/SignUpResponse.java
backend/src/main/java/com/movie/demo/member/service/MemberService.java
backend/src/main/java/com/movie/demo/member/service/MemberServiceImpl.java

[TC-4] 회원가입 구현

---

backend/gatchaPedia_BackEnd/build.gradle
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/handler/ExceptionManager.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/controller/MemberController.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/entity/Member.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/exception/MemberDuplicateByEmailException.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/exception/MemberDuplicateByNameException.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/exception/MemberDuplicateByUsernameException.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/exception/PasswordMisMatchException.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/request/LoginRequest.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/request/SignUpRequest.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/service/MemberService.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/service/MemberServiceImpl.java
backend/gatchaPedia_BackEnd/src/main/resources/application.yml

이미 존재하는 이메일, 아이디로 회원가입 하는 경우 예외 처리

[TC-6] 이미 존재하는 이메일, 아이디로 회원가입 하는 경우 예외 처리

---

backend/gatchaPedia_BackEnd/build.gradle
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/handler/SignUpExceptionManager.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/controller/MemberController.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/exception/DuplicateMemberByNameException.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/request/SignUpRequest.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/service/MemberServiceImpl.java

[TC-7] 회원가입 예외처리

---

backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/handler/SignUpExceptionManager.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/controller/MemberController.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/request/LoginRequest.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/service/MemberServiceImpl.java

[TC-8] 로그인 인증작업 예외 처리

---

backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/handler/SignUpExceptionManager.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/controller/MemberController.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/entity/Member.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/request/SignUpRequest.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/service/MemberService.java
backend/gatchaPedia_BackEnd/src/main/java/com/gatchaPedia/demo/member/service/MemberServiceImpl.java

[TC-9] 로그아웃 기능 구현

---

backend/src/main/java/com/gatchaPedia/demo/movie/controller/MovieController.java
backend/src/main/java/com/gatchaPedia/demo/movie/entity/Movie.java
backend/src/main/java/com/gatchaPedia/demo/movie/repository/MovieRepository.java
backend/src/main/java/com/gatchaPedia/demo/movie/response/Top100MovieListResponse.java
backend/src/main/java/com/gatchaPedia/demo/movie/response/Top100MovieResponse.java
backend/src/main/java/com/gatchaPedia/demo/movie/service/MovieService.java
backend/src/main/java/com/gatchaPedia/demo/movie/service/MovieServiceImpl.java

[TC-12] 별점순 영화 TOP 100 리스트 반환

---

frontend/src/routes/login.js

[TC-11] 로그인 페이지 구현

---

frontend/src/routes/mypage.js

[TC-27] 마이페이지 구현

---

frontend/src/routes/mypage.js

[TC-13] 회원탈퇴 페이지 구현

---

backend/src/main/java/com/gatchaPedia/demo/handler/LoginExcepitonManager.java
backend/src/main/java/com/gatchaPedia/demo/member/exception/MemberAuthException.java
backend/src/main/java/com/gatchaPedia/demo/member/response/MemberAuthFailResponse.java
backend/src/main/java/com/gatchaPedia/demo/member/service/MemberServiceImpl.java
backend/src/main/java/com/gatchaPedia/interceptor/LoginCheckInterceptor.java
backend/src/main/java/com/gatchaPedia/interceptor/WebConfig.java

[TC-24] 로그인 인가 처리

---

backend/src/main/java/com/gatchaPedia/demo/DemoApplication.java
backend/src/main/java/com/gatchaPedia/demo/interceptor/LoginCheckInterceptor.java
backend/src/main/java/com/gatchaPedia/demo/interceptor/WebConfig.java
backend/src/main/java/com/gatchaPedia/demo/movie/controller/MovieController.java
backend/src/main/java/com/gatchaPedia/demo/movie/entity/Movie.java
backend/src/main/java/com/gatchaPedia/demo/movie/response/MainPageResponse.java
backend/src/main/java/com/gatchaPedia/demo/movie/response/MovieRecomendResponse.java
backend/src/main/java/com/gatchaPedia/demo/movie/response/MovieRerollResponse.java
backend/src/main/java/com/gatchaPedia/demo/movie/service/MovieService.java
backend/src/main/java/com/gatchaPedia/demo/movie/service/MovieServiceImpl.java

[TC-23] 메인페이지 , 랜덤 영화 가챠 ãAPI 구현

---

backend/src/main/java/com/gatchaPedia/demo/movie/controller/MovieController.java
backend/src/main/java/com/gatchaPedia/demo/movie/request/AllMovieGetRequest.java
backend/src/main/java/com/gatchaPedia/demo/movie/response/AllMovieGetResponse.java
backend/src/main/java/com/gatchaPedia/demo/movie/response/MovieResponseForAllMovie.java
backend/src/main/java/com/gatchaPedia/demo/movie/service/MovieService.java
backend/src/main/java/com/gatchaPedia/demo/movie/service/MovieServiceImpl.java

[TC-19] 전체 영화 리스트 반환 구현

---

backend/build.gradle
backend/src/main/java/com/gatchaPedia/demo/bookmark/entity/Bookmark.java
backend/src/main/java/com/gatchaPedia/demo/bookmark/repository/BookmarkRepository.java
backend/src/main/java/com/gatchaPedia/demo/config/WebClientConfig.java
backend/src/main/java/com/gatchaPedia/demo/member/entity/Member.java
backend/src/main/java/com/gatchaPedia/demo/movie/controller/MovieController.java
backend/src/main/java/com/gatchaPedia/demo/movie/response/MovieRecomendResponse.java
backend/src/main/java/com/gatchaPedia/demo/movie/response/RecommendAPIResponse.java
backend/src/main/java/com/gatchaPedia/demo/movie/response/RecommendMovieInfo.java
backend/src/main/java/com/gatchaPedia/demo/movie/service/MovieService.java
backend/src/main/java/com/gatchaPedia/demo/movie/service/MovieServiceImpl.java

영화 추천 API 서버와 백엔드 서버 연결 , 북마크 기반 영화 추천 API

[TC-31] 영화 추천 API 서버와 백엔드 서버 연결 , 북마크 기반 영화 추천 API

---

python/api2csv.py

[TC-15] TMDB API로 영화 overview, photoUrl 받아온 후 csv 파일로 저장

[TC-15] TMDB API로 영화 overview, photoUrl 받아온 후 csv 파일로 저장

---

python/csv2db.py

[TC-32] csv 파일 DB에 저장하기

---

frontend/src/component/header.js
frontend/src/public/css/main.css
frontend/src/routes/information.js
frontend/src/routes/list.js
frontend/src/routes/login.js
frontend/src/routes/main.js
frontend/src/routes/register.js

[TC-17] 탈퇴 완료 표시 기능 구현

---

backend/src/main/java/com/gatchaPedia/demo/interceptor/LoginCheckInterceptor.java
backend/src/main/java/com/gatchaPedia/demo/member/entity/Member.java
backend/src/main/java/com/gatchaPedia/demo/movie/service/MovieServiceImpl.java
backend/src/main/resources/application.yml
python/app.py

백엔드 서버와 파이썬 서버 연결 후 북마크 기반 추천 영화리스트 받아오기

[TC-38] 백엔드 서버와 파이썬 서버 연결 후 북마크 기반 추천 영화리스트 받아오기

---

frontend/README.md
frontend/src/App.js
frontend/src/component/header.js
frontend/src/public/css/main.css
frontend/src/routes/information.js
frontend/src/routes/list.js
frontend/src/routes/main.js

[TC-37] 카테고리별 영화 조회 페이지 구현

---

backend/src/main/java/com/gatchaPedia/demo/genre/entity/Genre.java
backend/src/main/java/com/gatchaPedia/demo/interceptor/LoginCheckInterceptor.java
backend/src/main/java/com/gatchaPedia/demo/movie/entity/Movie.java
backend/src/main/java/com/gatchaPedia/demo/movie/response/MainPageResponse.java
backend/src/main/java/com/gatchaPedia/demo/movie/service/MovieServiceImpl.java
backend/src/main/java/com/gatchaPedia/demo/rating/entity/Rating.java
backend/src/main/java/com/gatchaPedia/demo/tag/entity/Tag.java
backend/src/main/resources/application.yml

[FIX] 잡 버그 수정

---

backend/src/main/java/com/gatchaPedia/demo/interceptor/WebConfig.java
backend/src/main/java/com/gatchaPedia/demo/movie/controller/MovieController.java
backend/src/main/java/com/gatchaPedia/demo/movie/response/MovieInfoResponse.java
backend/src/main/java/com/gatchaPedia/demo/movie/service/MovieService.java
backend/src/main/java/com/gatchaPedia/demo/movie/service/MovieServiceImpl.java
frontend/.idea/misc.xml

영화 상세페이지에서 이전에 북마크 체크 했었는지 확인 하기

[TC-21] 영화 상세페이지에서 이전에 북마크 체크 했었는지 확인 하기

---

frontend/src/App.js
frontend/src/component/header.js
frontend/src/public/css/main.css
frontend/src/routes/information.js
frontend/src/routes/list.js
frontend/src/routes/main.js
frontend/src/routes/mypage.js
frontend/src/setupProxy.js

[TC-16] 검색 화면 구현

---

backend/src/main/java/com/gatchaPedia/demo/bookmark/controller/BookmarkController.java
backend/src/main/java/com/gatchaPedia/demo/member/controller/MemberController.java
backend/src/main/java/com/gatchaPedia/demo/member/entity/Member.java
backend/src/main/java/com/gatchaPedia/demo/member/response/InvaildSessionCheckResponse.java
backend/src/main/java/com/gatchaPedia/demo/member/service/MemberService.java
backend/src/main/java/com/gatchaPedia/demo/member/service/MemberServiceImpl.java
backend/src/main/java/com/gatchaPedia/demo/movie/repository/MovieRepository.java
backend/src/main/java/com/gatchaPedia/demo/movie/service/MovieServiceImpl.java

[Tc 40] 회원탈퇴, 세션 유효 확인
